--1.L01Estado
CREATE TABLE LE01ESTADO (
  Sigla  CHAR(2)       NOT NULL,
  Nome   VARCHAR(100)  NOT NULL,

  CONSTRAINT PKESTADO PRIMARY KEY (Sigla),
  CONSTRAINT UNNOMEESTADO UNIQUE (Nome)
);

--2.L02Cidade
CREATE TABLE LE02CIDADE (
  Nome         VARCHAR(100)  NOT NULL,
  SiglaEstado  CHAR(2)       NOT NULL,

  Populacao    NUMBER(9)     NOT NULL,

  CONSTRAINT PKCIDADE PRIMARY KEY (Nome,SiglaEstado),
  CONSTRAINT FKESTADOCIDADE FOREIGN KEY (SiglaEstado)
     REFERENCES LE01ESTADO(Sigla) ON DELETE CASCADE,
  CONSTRAINT CKPOPULACAOCIDADE CHECK (Populacao >= 0)
);

--3.L03Zona
CREATE TABLE LE03ZONA (
  NroZona             NUMBER(6)  NOT NULL,
  NroDeUrnasReservas  NUMBER(2)  NOT NULL,

  CONSTRAINT PKZONA PRIMARY KEY (NroZona)
);

--4.L04Bairro
CREATE TABLE LE04BAIRRO (
  Nome         VARCHAR(100)  NOT NULL,
  NomeCidade   VARCHAR(100)  NOT NULL,
  SiglaEstado  CHAR(2)       NOT NULL,
  
  CEP          NUMBER(8),
  NroZona      NUMBER(6)     NOT NULL,

  CONSTRAINT PKBAIRRO PRIMARY KEY (Nome,NomeCidade,SiglaEstado),
  CONSTRAINT UNCEPBAIRRO UNIQUE (CEP),
  CONSTRAINT FKCIDADEBAIRRO FOREIGN KEY (NomeCidade,SiglaEstado)
     REFERENCES LE02CIDADE(Nome,SiglaEstado) ON DELETE CASCADE,
  CONSTRAINT FKZONABAIRRO FOREIGN KEY (NroZona)
     REFERENCES LE03ZONA(NroZona)
);

--5.L05URNA
CREATE TABLE LE05URNA (
  NSerial  NUMBER(9)  NOT NULL,
  Estado   VARCHAR(10),

  NroZona  NUMBER(6),

  CONSTRAINT PKURNA PRIMARY KEY (NSerial),
  CONSTRAINT FKZONAURNA FOREIGN KEY (NroZona)
     REFERENCES LE03ZONA(NroZona),
  CONSTRAINT CKESTADO CHECK(Estado IN ('funcional','manutencao'))
);

--6.L06Sessao
CREATE TABLE LE06SESSAO (
  NroSessao     NUMBER(5)  NOT NULL,

  NroZona       NUMBER(6),
  NSerial       NUMBER(9) NOT NULL,

  CONSTRAINT PKSESSAO PRIMARY KEY (NroSessao,NroZona),
  CONSTRAINT FKZONASESSAO FOREIGN KEY (NroZona)
     REFERENCES LE03ZONA(NroZona) ON DELETE CASCADE,
  CONSTRAINT FKURNASESSAO FOREIGN KEY (NSerial)
     REFERENCES LE05URNA(NSerial)
);

--7.LE07PARTIDO
CREATE TABLE LE07PARTIDO (
  Sigla  CHAR(5) NOT NULL,
  Nome   VARCHAR(100) NOT NULL,

  CONSTRAINT PKPARTIDO PRIMARY KEY (Sigla),
  CONSTRAINT UNNOMEPARTIDO UNIQUE (Nome)
);

--8.L08Candidato

CREATE TABLE LE08CANDIDATO (
  NroCand  NUMBER(9)  NOT NULL,
  Tipo     CHAR(8)    NOT NULL,

  CPF      NUMBER(11),
  Nome     VARCHAR(100) NOT NULL,
  Idade    NUMBER(3),
  Apelido  VARCHAR(100),

  SiglaPartido  CHAR(5),

  CONSTRAINT PKCANDIDATO PRIMARY KEY (NroCand),
  CONSTRAINT UNCPF UNIQUE (CPF),
  CONSTRAINT FKPARTIDOCANDIDATO FOREIGN KEY (SiglaPartido)
     REFERENCES LE07PARTIDO(Sigla),
  CONSTRAINT CKCANDIDATO CHECK (
     Tipo = 'politico' AND SiglaPartido IS NOT NULL AND CPF IS NOT NULL
     OR
     Tipo = 'especial' AND SiglaPartido IS NULL AND CPF IS NULL AND Idade IS NULL AND Apelido IS NULL)
);

--9.L09Cargo
-- a esfera federal não possui nem estado nem cidade, a estadual possui obrigatoriamente apenas estado, e a municipal possui obrigatoriamente estado e cidade;

CREATE TABLE LE09CARGO (
  CodCargo        NUMBER(9)     NOT NULL,

  PossuiVice      NUMBER(1)     NOT NULL,
  AnoBase         NUMBER(4)     NOT NULL,
  AnosMandato     NUMBER(1)     DEFAULT 4 NOT NULL,
  NomeDescritivo  VARCHAR(100)  NOT NULL,
  NroDeCadeiras     NUMBER(3)     NOT NULL,

  Esfera          VARCHAR(9)    NOT NULL,
  NomeCidade      VARCHAR(100),
  SiglaEstado     CHAR(2),

  CONSTRAINT PKCARGO PRIMARY KEY (CodCargo),
  CONSTRAINT UNNOMECARGO UNIQUE (NomeDescritivo, NomeCidade, SiglaEstado),
  CONSTRAINT CKCADEIRASCARGO CHECK (NroDeCadeiras > 0),
  CONSTRAINT CKANOSMANDATOCARGO CHECK (AnosMandato > 0),
  CONSTRAINT CKANOBASECARGO CHECK (AnoBase BETWEEN 1985 AND 2100),
  CONSTRAINT CKPOSSUIVICE CHECK (PossuiVice IN (0,1)),
  CONSTRAINT CKESFERACARGO CHECK (Esfera IN ('F','E','M')),
  CONSTRAINT CKATRIBUTOSESFERACARGO CHECK (
     (Esfera = 'F'
        AND NomeCidade  IS NULL
        AND SiglaEstado IS NULL)
     OR
     (Esfera = 'E'
        AND NomeCidade  IS NULL
        AND SiglaEstado IS NOT NULL)
     OR
     (Esfera = 'M'
        AND NomeCidade  IS NOT NULL
        AND SiglaEstado IS NOT NULL)
  ),
  CONSTRAINT FKESTADOCARGO FOREIGN KEY (SiglaEstado)
     REFERENCES LE01ESTADO(Sigla),
  CONSTRAINT FKCIDADECARGO FOREIGN KEY (NomeCidade,SiglaEstado)
     REFERENCES LE02CIDADE(Nome,SiglaEstado)
);

--10.L10Candidatura
-- há dois candidatos especiais - branco e nulo que se candidatam a todos os cargos, em todos os anos de eleicoes;
-- um candidato pode concorrer uma única vez por ano;
-- os cargos que possuem vice precisam ter um vice-candidato vinculado à candidatura; um candidato nao pode ser titular e vice no mesmo ano, e nao pode ser vice de mais do que uma candidatura no mesmo ano;

CREATE TABLE LE10CANDIDATURA (
  Reg           NUMBER(3)  NOT NULL,

  CodCargo      NUMBER(9)  NOT NULL,
  Ano           NUMBER(4)  NOT NULL,
  NroCand  NUMBER(11) NOT NULL,

  NroVice       NUMBER(11),

  CONSTRAINT PKREGCANDIDATURA PRIMARY KEY (Reg),
  CONSTRAINT UNCANDIDAT UNIQUE(CodCargo,Ano,NroCand),
  CONSTRAINT FKCANDIDATOCANDIDATURA FOREIGN KEY (NroCand)
     REFERENCES LE08CANDIDATO(NroCand),
  CONSTRAINT FKVICECANDIDATO FOREIGN KEY (NroVice)
     REFERENCES LE08CANDIDATO(NroCand),
  CONSTRAINT FKCARGOCANDIDATURA FOREIGN KEY (CodCargo)
     REFERENCES LE09CARGO(CodCargo),
  CONSTRAINT CKANOCANDIDATURA CHECK (Ano BETWEEN 1985 AND 2100)
);

--11.L11PLEITO
CREATE TABLE LE11PLEITO (
  NroSessao NUMBER(5)     NOT NULL,
  NroZona   NUMBER(6)     NOT NULL,

  CodCargo      NUMBER(9)  NOT NULL,
  Ano           NUMBER(4)  NOT NULL,
  NroCand  NUMBER(11) NOT NULL,  

  Total     NUMBER(9)     DEFAULT 0  NOT NULL,

  CONSTRAINT PKCOMPUTAVOTOS PRIMARY KEY(NroSessao,NroZona,CodCargo,Ano,NroCand),
  CONSTRAINT FKSESSAOCANDIDATURA FOREIGN KEY (NroSessao,NroZona)
     REFERENCES LE06SESSAO(NroSessao,NroZona),
  CONSTRAINT FKCANDIDATURASESSAO FOREIGN KEY (CodCargo,Ano,NroCand)
     REFERENCES LE10CANDIDATURA(CodCargo,Ano,NroCand)
);

--12.L12Pesquisa

CREATE TABLE LE12PESQUISA (
  RegPesquisa    NUMBER(9)     NOT NULL,
  PeriodoInicio  DATE          NOT NULL,
  PeriodoFim     DATE          NOT NULL,
  OrgaoPesquisa  VARCHAR(100) DEFAULT 'IBOPE',

  CONSTRAINT PKPESQUISA PRIMARY KEY (RegPesquisa),
  CONSTRAINT CKPERIODOPESQUISA CHECK (PeriodoFim > PeriodoInicio)
);


--13.L13IntencaoVotos
CREATE TABLE LE13INTENCAODEVOTO (
  RegPesquisa  NUMBER(9)  NOT NULL,
  RegCandid    NUMBER(3)  NOT NULL,

  Total     NUMBER(9)     DEFAULT 0  NOT NULL,

  CONSTRAINT PKCOMPINTENC PRIMARY KEY(RegPesquisa,RegCandid),
  CONSTRAINT FKPESQUISACANDIDATURA FOREIGN KEY (RegPesquisa)
     REFERENCES LE12PESQUISA(RegPesquisa),
  CONSTRAINT FKCANDIDATURAPESQUISA FOREIGN KEY (RegCandid)
     REFERENCES LE10CANDIDATURA(Reg)
);


CREATE SYNONYM LE13 FOR LE13INTENCAODEVOTO;
CREATE SYNONYM LE12 FOR LE12PESQUISA;
CREATE SYNONYM LE11 FOR LE11PLEITO;
CREATE SYNONYM LE10 FOR LE10CANDIDATURA;
CREATE SYNONYM LE09 FOR LE09CARGO;
CREATE SYNONYM LE08 FOR LE08CANDIDATO;
CREATE SYNONYM LE07 FOR LE07PARTIDO;
CREATE SYNONYM LE06 FOR LE06SESSAO;
CREATE SYNONYM LE05 FOR LE05URNA;
CREATE SYNONYM LE04 FOR LE04BAIRRO;
CREATE SYNONYM LE03 FOR LE03ZONA;
CREATE SYNONYM LE02 FOR LE02CIDADE;
CREATE SYNONYM LE01 FOR LE01ESTADO;

CREATE SYNONYM INTENCAODEVOTO FOR LE13INTENCAODEVOTO;
CREATE SYNONYM PESQUISA FOR LE12PESQUISA;
CREATE SYNONYM PLEITO FOR LE11PLEITO;
CREATE SYNONYM CANDIDATURA FOR LE10CANDIDATURA;
CREATE SYNONYM CARGO FOR LE09CARGO;
CREATE SYNONYM CANDIDATO FOR LE08CANDIDATO;
CREATE SYNONYM PARTIDO FOR LE07PARTIDO;
CREATE SYNONYM SESSAO FOR LE06SESSAO;
CREATE SYNONYM URNA FOR LE05URNA;
CREATE SYNONYM BAIRRO FOR LE04BAIRRO;
CREATE SYNONYM ZONA FOR LE03ZONA;
CREATE SYNONYM CIDADE FOR LE02CIDADE;
CREATE SYNONYM ESTADO FOR LE01ESTADO;

/*
DROP TABLE LE13INTENCAODEVOTO;
DROP TABLE LE12PESQUISA;
DROP TABLE LE11PLEITO;
DROP TABLE LE10CANDIDATURA;
DROP TABLE LE09CARGO;
DROP TABLE LE08CANDIDATO;
DROP TABLE LE07PARTIDO;
DROP TABLE LE06SESSAO;
DROP TABLE LE05URNA;
DROP TABLE LE04BAIRRO;
DROP TABLE LE03ZONA;
DROP TABLE LE02CIDADE;
DROP TABLE LE01ESTADO;

DROP SYNONYM LE13;
DROP SYNONYM LE12;
DROP SYNONYM LE11;
DROP SYNONYM LE10;
DROP SYNONYM LE09;
DROP SYNONYM LE08;
DROP SYNONYM LE07;
DROP SYNONYM LE06;
DROP SYNONYM LE05;
DROP SYNONYM LE04;
DROP SYNONYM LE03;
DROP SYNONYM LE02;
DROP SYNONYM LE01;

DROP SYNONYM INTENCAODEVOTO;
DROP SYNONYM PESQUISA;
DROP SYNONYM PLEITO;
DROP SYNONYM CANDIDATURA;
DROP SYNONYM CARGO;
DROP SYNONYM CANDIDATO;
DROP SYNONYM PARTIDO;
DROP SYNONYM SESSAO;
DROP SYNONYM URNA;
DROP SYNONYM BAIRRO;
DROP SYNONYM ZONA;
DROP SYNONYM CIDADE;
DROP SYNONYM ESTADO;
*/
